=== farao-community/gridcapa-core-valid-intraday/gridcapa-core-valid-intraday-app/src/main/resources/xsd/f645/flowbaseddomaindocument-25.xsd
<?xml version="1.0" encoding="UTF-8"?> <!-- UNI-LT CCt adaptation: ReceiverCategory added for timestamp code. Version increased to 24 (from 23) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ecc="etso-core-cmpts.xsd" xmlns:fb="flowbased" targetNamespace="flowbased" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<simpleType name="Direction_Type">
		<restriction base="string">
			<enumeration value="DIRECT"/>
			<enumeration value="OPPOSITE"/>
		</restriction>
	</simpleType>
	<simpleType name="ActionSetType_Type">
		<restriction base="string">
			<enumeration value="PREVENTIVE"/>
			<enumeration value="CURATIVE"/>
		</restriction>
	</simpleType>
	<simpleType name="MinMax_Type">
		<restriction base="string">
			<enumeration value="MIN"/>
			<enumeration value="MAX"/>
		</restriction>
	</simpleType>
	<simpleType name="BranchStatus_Type">
		<restriction base="string">
			<enumeration value="OK"/>
			<enumeration value="OUT"/>
		</restriction>
	</simpleType>
	<simpleType name="OutageStatus_Type">
		<restriction base="string">
			<enumeration value="N-K"/>
			<enumeration value="N"/>
		</restriction>
	</simpleType>
	<simpleType name="OutageType_Type"> <!-- Alegro/CEP -->
		<restriction base="string">
			<enumeration value="branch"/>
			<enumeration value="load"/>
			<enumeration value="generation"/>
			<enumeration value="node"/>
			<enumeration value="hvdc"/>
			<enumeration value="hvdcVH"/>
		</restriction>
	</simpleType>
	<simpleType name="DomainStatus_Type">
		<restriction base="string">
			<enumeration value="ok"/>
			<enumeration value="unbounded"/>
			<enumeration value="empty"/>
			<enumeration value="0volume"/>
		</restriction>
	</simpleType>
	<simpleType name="RemedialActionApply_Type">
		<restriction base="string">
			<enumeration value="Applied"/>
			<enumeration value="NotApplied"/>
		</restriction>
	</simpleType>
	<simpleType name="nonEmptyString">
		<restriction base="string">
			<minLength value="1"/>
		</restriction>
	</simpleType>
	<element name="FlowBasedDomainDocument">
		<complexType>
			<sequence>
				<element name="DocumentIdentification" type="ecc:IdentificationType"/>
				<element name="DocumentVersion" type="ecc:VersionType"/>
				<element name="DocumentType" type="ecc:MessageType"/>
				<element name="ProcessType" type="ecc:ProcessType"/>
				<element name="SenderIdentification" type="ecc:PartyType"/>
				<element name="SenderRole" type="ecc:RoleType"/>
				<element name="ReceiverIdentification" type="ecc:PartyType"/>
				<element name="ReceiverRole" type="ecc:RoleType"/>
				<element name="ReceiverCategory" type="ecc:CodeType" minOccurs="0" maxOccurs="1"/> <!-- Added. Optional. CodeType = string with max length 3 -->
				<element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<element name="FlowBasedDomainTimeInterval" type="ecc:TimeIntervalType"/>
				<element name="Domain" type="ecc:AreaType"/>
				<element name="FlowBasedDomainTimeSeries" type="fb:FlowBasedDomainTimeSeries_Type" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="DtdVersion" type="string" use="required"/>
			<attribute name="DtdRelease" type="string" use="required"/>
		</complexType>
	</element>
	<complexType name="FlowBasedDomainTimeSeries_Type">
		<sequence>
			<element name="TimeSeriesIdentification" type="ecc:IdentificationType"/>
			<element name="BusinessType" type="ecc:BusinessType"/>
			<element name="Product" type="ecc:EnergyProductType"/>
			<element name="BalanceArea" type="ecc:AreaType"/>
			<element name="Period" type="fb:Period_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Period_Type">
		<sequence>
			<element name="TimeInterval" type="ecc:TimeIntervalType"/>
			<element name="Resolution" type="ecc:ResolutionType"/>
			<element name="Interval" type="fb:Interval_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Interval_Type">
		<sequence>
			<element name="Pos" type="ecc:PositionType"/>
			<element name="FlowBasedDomain" type="fb:FlowBasedDomain_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FlowBasedDomain_Type">
		<sequence>
			<element name="constraintResults" type="fb:ConstResults_Type" minOccurs="0"/>
			<element name="vertices" type="fb:Vertices_Type" minOccurs="0"/>
			<element name="maxBexs" type="fb:MaxBexs_Type" minOccurs="0"/>
			<element name="limitNetPositions" type="fb:LimitNetPositions_Type" minOccurs="0"/>
			<element name="networkName" type="string" minOccurs="0"/>
			<element name="slackNode" type="string" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="string" use="optional"/>
		<attribute name="domainStatus" type="fb:DomainStatus_Type" use="optional"/>
	</complexType>
	<complexType name="ConstResults_Type">
		<sequence>
			<element name="constraintResult" type="fb:ConstResult_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ConstResult_Type">
		<sequence>
			<element name="criticalBranch" type="fb:CriticalBranch_Type" minOccurs="0"/>
			<element name="ptdfs" type="fb:Ptdfs_Type" minOccurs="0"/>
			<element name="z2zPtdfs" type="fb:Z2zPtdfs_Type" minOccurs="0"/>
			<element name="domainLimit" type="fb:DomainLimit_Type" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="type" type="fb:ConstraintType_Type"/>
	</complexType>
	<simpleType name="ConstraintType_Type">
		<restriction base="string">
			<enumeration value="BRANCH"/>
			<enumeration value="NET_POSITION"/>
			<enumeration value="EQUALITY_CONSTRAINT"/>
		</restriction>
	</simpleType>
	<complexType name="Ptdfs_Type">
		<sequence>
			<element name="ptdf" type="fb:Ptdf_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Z2zPtdfs_Type">
		<sequence>
			<element name="z2zPtdf" type="fb:Z2zPtdf_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DomainLimit_Type">
		<sequence>
			<element name="region" type="boolean" minOccurs="0"/>
			<element name="tso" type="boolean" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="CriticalBranch_Type">
		<sequence>
			<element name="complexVariant" type="fb:ComplexVariant_Type" minOccurs="0"/>
			<element name="monitoredBranch" type="fb:MonitoredBranch_Type" minOccurs="0"/>
			<element name="branchStatus" type="fb:BranchStatus_Type" minOccurs="0"/>
			<element name="branchStatusReason" type="string" minOccurs="0"/>
			<element name="direction" type="fb:Direction_Type" minOccurs="1"/>
			<element name="cva" type="float" minOccurs="0"/>
			<element name="iva" type="float" minOccurs="0"/>
			<element name="ivaShare" type="float" minOccurs="0"/>
			<element name="uva" type="float" minOccurs="0"/>
			<element name="ltaMargin" type="float" minOccurs="0"/>
			<element name="fMax" type="float" minOccurs="0"/>
			<element name="fLtaMax" type="float" minOccurs="0"/>
			<element name="fRef" type="float" minOccurs="0"/>
			<element name="frmMw" type="float" minOccurs="0"/>
			<element name="iMaxType" type="string" minOccurs="0"/>
			<element name="iMaxA" type="float" minOccurs="0"/>
			<element name="smv" type="float" minOccurs="0"/>
			<element name="amr" type="float" minOccurs="0"/>
			<element name="fUaf" type="float" minOccurs="0"/>
			<element name="f0All" type="float" minOccurs="0"/>
			<element name="f0Core" type="float" minOccurs="0"/>				
			<element name="minRAMfactor" type="float" minOccurs="0"/>
			<element name="CNEC" type="boolean" minOccurs="1"/>
			<element name="MNEC" type="boolean" minOccurs="0"/>
			<element name="maxZ2ZPTDF" type="float" minOccurs="1"/>
			<element name="maxZ2ZBorder" type="fb:MaxZ2ZBorder_Type" minOccurs="1"/>
			<element name="ftotalLtn" type="float" minOccurs="0"/>
			<element name="fAac" type="float" minOccurs="0"/>
			<!-- ftotalLTN which is equal to f0Core+fLtn. Fltn is calculated according to eq.22 of DA CCM.)-->
			<element name="outage" type="fb:Outage_Type" minOccurs="0"/>
			<element name="RAM0core" type="float" minOccurs="0"/>
			<!-- Following RAM elements below to be exported at different computation stages: -->
			<!--initial-->
			<!-- RAM=Fmax-FRM-Fref (virgin RAM at refprog in the export of initial computation) -->
			<!--intermediate-->
			<!-- RAM=Fmaxâ€“FRM-Fref+AMR+LTAmargin (RAM at refprog in the export of intermediate computation) -->
			<!--final-->
			<!-- RAM=RAMbn-Fltn according to eq.23=(Fmax-FRM-F0CORE+AMR+LTAmargin-CVA-IVA)-Fltn  -->
			<element name="RAM" type="float" minOccurs="0"/>
			<element name="ram_rel" type="float" minOccurs="0"/>
			<element name="tsoOrigin" type="fb:Name_Type"/>
			<element name="fromArea" type="ecc:IdentificationType" minOccurs="0"/>
			<element name="toArea" type="ecc:IdentificationType" minOccurs="0"/>
			<element name="ShadowPriceAmount" type="ecc:AmountType" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="originalId" type="string" use="optional"/>
	</complexType>
	<complexType name="MaxZ2ZBorder_Type">
		<attribute name="from" type="fb:Name_Type" use="required"/>
		<attribute name="to" type="fb:Name_Type" use="optional"/>
	</complexType>
	<complexType name="Outage_Type">
		<sequence>
			<element name="Status" type="fb:OutageStatus_Type" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="string" use="optional"/>
		<attribute name="eic" type="fb:nonEmptyString" use="optional"/>
		<attribute name="type" type="fb:OutageType_Type" use="optional"/> <!-- Alegro -->
	</complexType>
	<complexType name="ComplexVariant_Type">
		<sequence>
			<element name="actionSets" type="fb:ActionSets_Type" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="string" use="optional"/>
	</complexType>
	<complexType name="ActionSets_Type">
		<sequence>
			<element name="actionSet" type="fb:ActionSet_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ActionSet_Type">
		<sequence>
			<element name="type" type="fb:ActionSetType_Type" minOccurs="0"/>
			<element name="status" type="fb:RemedialActionApply_Type" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="string" use="optional"/>
	</complexType>
	<complexType name="MonitoredBranch_Type">
		<sequence>
			<element name="inGrid" type="fb:Branch_Type" minOccurs="0"/>
			<element name="specified" type="fb:Branch_Type" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="eic" type="fb:nonEmptyString" use="optional"/>
	</complexType>
	<complexType name="Branch_Type">
		<sequence>
			<element name="from" type="fb:Node_Type"/>
			<element name="to" type="fb:Node_Type"/>
			<element name="elementName" type="string" minOccurs="0"/>
			<element name="order" type="string" minOccurs="0"/>
			<element name="direction" type="fb:Direction_Type" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="string" use="optional"/>
	</complexType>
	<simpleType name="TypeConstraint">
		<restriction base="string">
			<enumeration value="criticalBranch"/>
			<enumeration value="external"/>
		</restriction>
	</simpleType>
	<simpleType name="Name_Type">
		<restriction base="string">
			<pattern value="[a-zA-Z0-9_]{2,40}"/><!-- Extended length for Virtual Hubs -->
		</restriction>
	</simpleType>
	<simpleType name="NodeName_Type">
		<restriction base="string">
			<pattern value=".{6}\d(\p{L}|\d| )?"/>
		</restriction>
	</simpleType>
	<complexType name="Node_Type">
		<attribute name="name" type="fb:NodeName_Type" use="required"/>
		<attribute name="id" type="string" use="optional"/>
	</complexType>
	<complexType name="Ptdf_Type">
		<sequence>
			<element name="hub" type="fb:Hub_Type"/>
			<element name="value" type="float"/>
		</sequence>
	</complexType>
	<complexType name="Z2zPtdf_Type">
		<sequence>
			<element name="from" type="fb:Hub_Type"/>
			<element name="to" type="fb:Hub_Type"/>
			<element name="value" type="float"/>
		</sequence>
	</complexType>
	<complexType name="Hub_Type">
		<attribute name="name" type="fb:Name_Type" use="required"/>
		<attribute name="id" type="string" use="optional"/>
		<attribute name="techCounterparty" type="string" use="optional"/>
	</complexType>
	<complexType name="Vertices_Type">
		<sequence>
			<element name="vertex" type="fb:Vertex_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Vertex_Type">
		<sequence>
			<element name="coordinates" type="fb:Coordinates_Type" minOccurs="0"/>
			<element name="constraints" type="fb:Constraints_Type" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="Coordinates_Type">
		<sequence>
			<element name="coordinate" type="fb:Coordinate_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Coordinate_Type">
		<sequence>
			<element name="hub" type="fb:Hub_Type"/>
			<element name="value" type="float"/>
		</sequence>
	</complexType>
	<complexType name="Constraints_Type">
		<sequence>
			<element name="constraintResult" type="fb:ConstResult_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="MaxBexs_Type">
		<sequence>
			<element name="maxbex" type="fb:MaxBex_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="MaxBex_Type">
		<sequence>
			<element name="constraints" type="fb:Constraints_Type" minOccurs="0" maxOccurs="unbounded"/>
			<element name="fromhub" type="fb:Hub_Type"/>
			<element name="tohub" type="fb:Hub_Type"/>
			<element name="value" type="float"/>
		</sequence>
	</complexType>
	<complexType name="LimitNetPositions_Type">
		<sequence>
			<element name="limitnetposition" type="fb:LimitNetPosition_Type" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="LimitNetPosition_Type">
		<sequence>
			<element name="coordinates" type="fb:Coordinates_Type" minOccurs="0"/>
			<element name="constraints" type="fb:Constraints_Type" minOccurs="0"/>
			<element name="type" type="fb:MinMax_Type"/>
			<element name="hub" type="fb:Hub_Type"/>
		</sequence>
	</complexType>
</schema>

=== farao-community/gridcapa-core-valid-intraday/gridcapa-core-valid-intraday-app/src/test/resources/20250921-0000-FID2-645-INIT_VIRG_REFBAL_PRES_FBPARAMS-v3.xml
<?xml version="1.0" encoding="UTF-8"?><FlowBasedDomainDocument xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbaseddomaindocument-25.xsd" DtdVersion="0" DtdRelease="0">
  <DocumentIdentification v="ID2CCCt-20250921FID2-645v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="B08"/>
  <ProcessType v="A02"/>
  <SenderIdentification codingScheme="A01" v="XXXXXXXXXXXXXXXX"/>
  <SenderRole v="A36"/>
  <ReceiverIdentification codingScheme="A01" v="XXXXXXXXXXXXXXXX"/>
  <ReceiverRole v="A04"/>
  <CreationDateTime v="2025-09-20T18:34:05Z"/>
  <FlowBasedDomainTimeInterval v="2025-09-20T22:00Z/2025-09-20T23:00Z"/>
  <Domain codingScheme="A01" v="XXXXXXXXXXXXXXXX"/>
  <FlowBasedDomainTimeSeries>
    <TimeSeriesIdentification v="1"/>
    <BusinessType v="A06"/>
    <Product v="XXXXXXXXXXXXX"/>
    <BalanceArea codingScheme="A01" v="XXXXXXXXXXXXXXXX"/>
    <Period>
      <TimeInterval v="2025-09-20T22:00Z/2025-09-20T23:00Z"/>
      <Resolution v="PT60M"/>
      <Interval>
        <Pos v="1"/>
        <FlowBasedDomain id="DACF_REFPROG" name="REFPROG" domainStatus="ok">
          <constraintResults>
            <constraintResult id="XXXXXXXXXXXX" type="BRANCH">
              <criticalBranch id="CCCCCCCCCCCC">
                <monitoredBranch name="[AT-AT] Phyrn - Weissenbach 201A [DIR]" eic="XXXXXXXXXXXXXXXX">
                  <inGrid id="XXXXXXXXXXXXXXXX">
                    <from name="YYYYYYY"/>
                    <to name="XXXXXXXX"/>
                    <elementName>102A</elementName>
                    <order>1</order>
                  </inGrid>
                  <specified id="XXXXXXXXXXXXXXXX">
                    <from name="YYYYYYY"/>
                    <to name="XXXXXXXX"/>
                    <elementName>102A</elementName>
                    <direction>DIRECT</direction>
                  </specified>
                </monitoredBranch>
                <branchStatus>OK</branchStatus>
                <direction>DIRECT</direction>
                <iva>0</iva>
                <uva>0</uva>
                <fMax>100</fMax>
                <fRef>10</fRef>
                <frmMw>10</frmMw>
                <iMaxType>SEASONAL</iMaxType>
                <iMaxA>1000</iMaxA>
                <fUaf>0</fUaf>
                <f0All>20</f0All>
                <f0Core>10</f0Core>
                <CNEC>false</CNEC>
                <maxZ2ZPTDF>0.09</maxZ2ZPTDF>
                <maxZ2ZBorder from="CZ" to="SI"/>
                <outage name="BASECASE">
                  <Status>N</Status>
                </outage>
                <RAM0core>100</RAM0core>
                <RAM>100</RAM>
                <tsoOrigin>AT</tsoOrigin>
              </criticalBranch>
              <ptdfs>
                <ptdf>
                  <hub name="AT"/>
                  <value>0.000100</value>
                </ptdf>
                <ptdf>
                  <hub name="BE"/>
                  <value>0.000100</value>
                </ptdf>
                <ptdf>
                  <hub name="BE_AL"/>
                  <value>0.0001</value>
                </ptdf>
                <ptdf>
                  <hub name="CZ"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="DE"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="DE_AL"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="FR"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="HR"/>
                  <value>-0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="HU"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="NL"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="PL"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="RO"/>
                  <value>0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="SI"/>
                  <value>-0.001</value>
                </ptdf>
                <ptdf>
                  <hub name="SK"/>
                  <value>0.001</value>
                </ptdf>
              </ptdfs>
              <domainLimit>
                <region>false</region>
                <tso>false</tso>
              </domainLimit>
            </constraintResult>
          </constraintResults>
        </FlowBasedDomain>
        <FlowBasedDomain id="DACF_ZEROBALANCE" name="ZEROBALANCE"/>
      </Interval>
    </Period>
  </FlowBasedDomainTimeSeries>
</FlowBasedDomainDocument>
